* The candidate established technical credibility during the session.
** YES: The candidate was able to describe each AWS service used in the customer’s architecture and explained how the architecture achieves business outcomes. They articulated how the Well-Architected framework applies to the solution, answered the majority of questions about the services in in the customer’s architecture, and was able to effectively defer items for later discussion. • 100 Level is able to articulate the information provided on marketing pages for a service. • 200 Level is able to articulate the information provided on the FAQ for a service. • 300 Level is able to articulate how the service works and interacts with other services.*****************************
** NEEDS IMPROVEMENT: The candidate constantly deferred questions that are answered on the marketing and FAQ pages and could not explain how the architecture meets customer requirements. ******************************************NO: Candidate provided inaccurate information on services and could not justify architectural decisions.
* The candidate elicited current-state and future-state requirements.
** YES: The candidate asked clarifying questions naturally and within the flow of the conversation. The candidate was able to dive deep and ask probing questions about the customer’s workload and the business drivers supporting the migration to the cloud.********************NEEDS IMPROVEMENT: The candidate asked questions, but the questions interrupted the flow of the conversation by changing topics before the customer could provide an answer. Candidate didn’t clarify ambiguities or contradictions in requirements.**********************
** NO: The candidate did not ask customer about requirements and avoided talking about business drivers.
* The candidate engaged effectively with all participants.
** YES:The candidate engaged with each participant and solicited feedback to identify objections or concerns. Any objections, off-topic questions, or unanswered questions were captured for another meeting. These items were reviewed at end of the meeting and may need to be addressed in AWSome Builder III.********************NEEDS IMPROVEMENT: Candidate failed to engage with ‘quieter’ participants or failed to park objections or discussions that were not directly related to the problem being discussed.*******************
** NO: The candidate ignored concerns and objections raised by participants.
* The candidate secured a next meeting with the customer with clear timeline and scope.
** YES: The customer agreed to a demo and candidate has explained the timelines and scope for delivery. The solution meets or surpasses the requirements and business drivers. A strong candidate was able to “Think Big” with customer and demonstrated how AWS can increase the scope, scale, or effectiveness of the solution.***************NEEDS IMPROVEMENT: The candidate proposed a demo, but did not capture specific proof points that are most important to the customer. The customer did not know what to expect from the demo. **********************
** NO: The candidate did not ask the customer for a meeting to show a demo of the solution. The candidate did not earn trust with the customer and the customer felt there was no value using AWS.
* The candidate showed appropriate white-boarding skills.
** YES: Candidate actively used the whiteboard to capture details from the meeting in a clear, concise manner. A photo of the whiteboard should be sufficient for summarizing the meeting and decisions made.********************NEEDS IMPROVEMENT: Did not use whiteboard space effectively (constantly erasing or redrawing). Talked to the whiteboard instead of talking to the audience.***************
** NO: Diagrams and words were not legible. Whiteboard was an after-thought and not used during conversation. A picture of the whiteboard seemed more like an art project than an architecture diagram.
